language: node_js
node_js: "6.6.0"

before_script:
  - npm install
  
services: mongodb
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server

branches:
  only: master

script:
  - npm run test