language: node_js
node_js: "6.6.0"

before_script:
  - npm install
  
services: mongodb
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server

branches:
  only: master

script:
  - npm run test

deploy:
  provider: heroku
  app: meyespace-userservice # optional if it's the same as your repo name
  api_key: eb82729d-4018-488c-b4cb-7390a234b192